#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libepubgen
Version  : 0.1.1
Release  : 2
URL      : https://dev-www.libreoffice.org/src/libepubgen-0.1.1.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libepubgen-0.1.1.tar.xz
Summary  : EPUB generator library for librevenge
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libepubgen-lib
Requires: libepubgen-license
BuildRequires : boost-dev
BuildRequires : doxygen
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(librevenge-0.0)

%description
libepubgen is a library for generating documents in (surprise!) EPUB format,
implementing librevenge document interfaces. It supports conversion of text
documents, presentations and vector drawings. Spreadsheets are not supported,
because conversion of a spreadsheet to EPUB does not (IMHO) make much sense. As
these interfaces are used by multiple libraries, libepubgen can be used to
generate EPUB from many sources.

%package dev
Summary: dev components for the libepubgen package.
Group: Development
Requires: libepubgen-lib
Provides: libepubgen-devel

%description dev
dev components for the libepubgen package.


%package doc
Summary: doc components for the libepubgen package.
Group: Documentation

%description doc
doc components for the libepubgen package.


%package lib
Summary: lib components for the libepubgen package.
Group: Libraries
Requires: libepubgen-license

%description lib
lib components for the libepubgen package.


%package license
Summary: license components for the libepubgen package.
Group: Default

%description license
license components for the libepubgen package.


%prep
%setup -q -n libepubgen-0.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534629117
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534629117
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libepubgen
cp COPYING %{buildroot}/usr/share/doc/libepubgen/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libepubgen-0.1/libepubgen/EPUBDrawingGenerator.h
/usr/include/libepubgen-0.1/libepubgen/EPUBPackage.h
/usr/include/libepubgen-0.1/libepubgen/EPUBPresentationGenerator.h
/usr/include/libepubgen-0.1/libepubgen/EPUBTextGenerator.h
/usr/include/libepubgen-0.1/libepubgen/libepubgen-api.h
/usr/include/libepubgen-0.1/libepubgen/libepubgen-decls.h
/usr/include/libepubgen-0.1/libepubgen/libepubgen.h
/usr/lib64/libepubgen-0.1.so
/usr/lib64/pkgconfig/libepubgen-0.1.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libepubgen/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libepubgen-0.1.so.1
/usr/lib64/libepubgen-0.1.so.1.0.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/libepubgen/COPYING
